# Generated by Django 5.2.17 on 2026-10-01 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("sp_api", "Amazon SP-API"),
                            ("dummy", "Dummy Amazon client"),
                            ("export", "Seller Central export"),
                        ],
                        max_length=16,
                    ),
                ),
                ("report_type", models.CharField(blank=True, max_length=128)),
                ("data_start", models.DateTimeField(blank=True, null=True)),
                ("data_end", models.DateTimeField(blank=True, null=True)),
                (
                    "fetched_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this data was known to be true (download time).",
                    ),
                ),
                ("file", models.FileField(upload_to="raw_reports/%Y/%m/")),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("sha256", models.CharField(max_length=64)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("order_count", models.PositiveIntegerField(default=0)),
                (
                    "new_versions",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orders that were new or changed in this report.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_reports",
                        to="catalog.brand",
                    ),
                ),
            ],
            options={
                "ordering": ["-fetched_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amazon_order_id", models.CharField(max_length=32)),
                ("fetched_at", models.DateTimeField()),
                ("last_updated_date", models.DateTimeField(blank=True, null=True)),
                ("order_status", models.CharField(blank=True, max_length=32)),
                ("content_hash", models.CharField(max_length=64)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_versions",
                        to="catalog.brand",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_versions",
                        to="sales.rawreport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("orders", "Orders"),
                            ("traffic", "Sales & traffic"),
                            ("ads", "Sponsored ads"),
                            ("dsp", "DSP"),
                            ("subscriptions", "Subscribe & Save"),
                        ],
                        default="orders",
                        max_length=16,
                    ),
                ),
                ("client", models.CharField(max_length=16)),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("reports", models.PositiveIntegerField(default=0)),
                ("new_versions", models.PositiveIntegerField(default=0)),
                ("message", models.TextField(blank=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_runs",
                        to="catalog.brand",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amazon_order_id", models.CharField(max_length=32)),
                ("purchase_date", models.DateTimeField(null=True)),
                (
                    "purchase_day",
                    models.DateField(
                        help_text="Purchase date in REPORT_TIME_ZONE; used for day/week/month grouping.",
                        null=True,
                    ),
                ),
                ("order_status", models.CharField(blank=True, max_length=32)),
                ("item_status", models.CharField(blank=True, max_length=32)),
                ("fulfillment_channel", models.CharField(blank=True, max_length=32)),
                ("sales_channel", models.CharField(blank=True, max_length=64)),
                ("asin", models.CharField(blank=True, max_length=10)),
                ("sku", models.CharField(blank=True, max_length=64)),
                ("product_name", models.TextField(blank=True)),
                ("quantity", models.IntegerField(null=True)),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "item_price",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "item_tax",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "shipping_price",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "item_promotion_discount",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "ship_promotion_discount",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("is_business_order", models.BooleanField(null=True)),
                ("raw", models.JSONField()),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.brand",
                    ),
                ),
                (
                    "marketplace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.marketplace",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.orderversion",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["brand", "purchase_day"],
                        name="sales_order_brand_i_2ed239_idx",
                    ),
                    models.Index(
                        fields=["brand", "asin"], name="sales_order_brand_i_0b0bf0_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="rawreport",
            constraint=models.UniqueConstraint(
                fields=("brand", "sha256"), name="unique_raw_report_per_brand"
            ),
        ),
        migrations.AddIndex(
            model_name="orderversion",
            index=models.Index(
                fields=["brand", "amazon_order_id", "fetched_at"],
                name="sales_order_brand_i_c21f1d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orderversion",
            index=models.Index(
                fields=["brand", "is_current"], name="sales_order_brand_i_268dc1_idx"
            ),
        ),
    ]
