# Generated by Django 5.2.17 on 2026-10-01 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataPull",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("traffic", "Sales & traffic report"),
                            ("ads", "Sponsored ads reports"),
                            ("dsp", "DSP report"),
                            ("subscriptions", "Subscribe & Save metrics"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source", models.CharField(max_length=16)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("fetched_at", models.DateTimeField(db_index=True)),
                ("file", models.FileField(upload_to="data_pulls/%Y/%m/")),
                ("days", models.PositiveIntegerField(default=0)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_pulls",
                        to="catalog.brand",
                    ),
                ),
                (
                    "marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.marketplace",
                    ),
                ),
            ],
            options={
                "ordering": ["-fetched_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyTraffic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "ordered_product_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("units_ordered", models.IntegerField(default=0)),
                ("sessions", models.IntegerField(default=0)),
                ("page_views", models.IntegerField(default=0)),
                (
                    "average_offer_count",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "buy_box_percentage",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.brand",
                    ),
                ),
                (
                    "marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.marketplace",
                    ),
                ),
                (
                    "pull",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="performance.datapull",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("brand", "marketplace", "date"),
                        name="unique_daily_traffic",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailySubscriptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("active_subscriptions", models.IntegerField(default=0)),
                ("shipped_units", models.IntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.brand",
                    ),
                ),
                (
                    "marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.marketplace",
                    ),
                ),
                (
                    "pull",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="performance.datapull",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("brand", "marketplace", "date"),
                        name="unique_daily_subscriptions",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyAds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "ad_product",
                    models.CharField(
                        choices=[
                            ("SP", "Sponsored Products"),
                            ("SB", "Sponsored Brands"),
                            ("SD", "Sponsored Display"),
                            ("DSP", "DSP"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Attributed sales: 7-day for Sponsored Products, 14-day for the others.",
                        max_digits=14,
                    ),
                ),
                ("impressions", models.BigIntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                ("orders", models.IntegerField(default=0)),
                ("units", models.IntegerField(default=0)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.brand",
                    ),
                ),
                (
                    "marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.marketplace",
                    ),
                ),
                (
                    "pull",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="performance.datapull",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("brand", "marketplace", "date", "ad_product"),
                        name="unique_daily_ads",
                    )
                ],
            },
        ),
    ]
