from decimal import Decimal

# Generated by Django 5.2.17 on 2026-10-01 05:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


# The stores every installation starts with. Rates and names are editable later.
MARKETPLACES = [
    # code, name, marketplace id, sales channel, currency, usd rate, sort
    ("US", "United States", "ATVPDKIKX0DER", "Amazon.com", "USD", Decimal("1"), 1),
    ("CA", "Canada", "A2EUQ1WTGCTBG2", "Amazon.ca", "CAD", Decimal("0.73"), 2),
]


def create_marketplaces(apps, schema_editor):
    Marketplace = apps.get_model("catalog", "Marketplace")
    for code, name, mid, channel, currency, rate, sort in MARKETPLACES:
        Marketplace.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "amazon_marketplace_id": mid,
                "sales_channel": channel,
                "currency": currency,
                "usd_rate": rate,
                "sort_order": sort,
            },
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Marketplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code, e.g. US or CA.",
                        max_length=8,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("amazon_marketplace_id", models.CharField(max_length=32, unique=True)),
                (
                    "sales_channel",
                    models.CharField(
                        help_text="Value of the 'sales-channel' column in Amazon order reports, e.g. Amazon.com.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                (
                    "usd_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1"),
                        help_text="Multiply amounts in this marketplace's currency by this to get USD. Used when combining stores.",
                        max_digits=10,
                        verbose_name="USD exchange rate",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used in URLs.", max_length=64, unique=True
                    ),
                ),
                (
                    "selling_partner_id",
                    models.CharField(
                        blank=True,
                        help_text="Merchant token of the seller account (returned when the app is authorized).",
                        max_length=64,
                        verbose_name="Selling partner ID",
                    ),
                ),
                (
                    "refresh_token_encrypted",
                    models.TextField(blank=True, editable=False),
                ),
                (
                    "sync_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Include this brand in scheduled Amazon syncs.",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "marketplaces",
                    models.ManyToManyField(
                        blank=True, related_name="brands", to="catalog.marketplace"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asin",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z0-9]{10}$",
                                "An ASIN is 10 characters: capital letters and digits.",
                            )
                        ],
                        verbose_name="ASIN",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Short name shown in reports.",
                        max_length=255,
                    ),
                ),
                (
                    "amazon_title",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Latest product name seen from Amazon.",
                        max_length=500,
                    ),
                ),
                (
                    "sku",
                    models.CharField(blank=True, max_length=64, verbose_name="SKU"),
                ),
                ("category", models.CharField(blank=True, max_length=128)),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("launch_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.brand",
                    ),
                ),
            ],
            options={
                "ordering": ["title", "asin"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("brand", "asin"), name="unique_product_asin_per_brand"
                    )
                ],
            },
        ),
        migrations.RunPython(create_marketplaces, migrations.RunPython.noop),
    ]
